// SPDX-License-Identifier: LGPL-3.0-only
//
// Currencies: ISO 4217 list one, SIX Group, published 2026-09-17 (https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml).
// `decimals` is the ISO minor unit: amounts are stored as integers of that unit.
// French names from Unicode CLDR (ICU of Node.js).
//
// Generated by scripts/data/generate-base-data.mjs — do not edit by hand.
import { defineData } from '@socle/framework';

export default defineData('res.currency', [
  {
    id: 'aed',
    values: {
      code: 'AED',
      name: 'dirham des Émirats arabes unis',
      numericCode: '784',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'afn',
    values: { code: 'AFN', name: 'afghani afghan', numericCode: '971', decimals: 2, active: false },
  },
  {
    id: 'all',
    values: { code: 'ALL', name: 'lek albanais', numericCode: '008', decimals: 2, active: false },
  },
  {
    id: 'amd',
    values: { code: 'AMD', name: 'dram arménien', numericCode: '051', decimals: 2, active: false },
  },
  {
    id: 'aoa',
    values: {
      code: 'AOA',
      name: 'kwanza angolais',
      numericCode: '973',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ars',
    values: { code: 'ARS', name: 'peso argentin', numericCode: '032', decimals: 2, active: false },
  },
  {
    id: 'aud',
    values: {
      code: 'AUD',
      name: 'dollar australien',
      numericCode: '036',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'awg',
    values: { code: 'AWG', name: 'florin arubais', numericCode: '533', decimals: 2, active: false },
  },
  {
    id: 'azn',
    values: { code: 'AZN', name: 'manat azéri', numericCode: '944', decimals: 2, active: false },
  },
  {
    id: 'bam',
    values: {
      code: 'BAM',
      name: 'mark convertible bosniaque',
      numericCode: '977',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bbd',
    values: {
      code: 'BBD',
      name: 'dollar barbadien',
      numericCode: '052',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bdt',
    values: {
      code: 'BDT',
      name: 'taka bangladeshi',
      numericCode: '050',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bhd',
    values: { code: 'BHD', name: 'dinar bahreïni', numericCode: '048', decimals: 3, active: false },
  },
  {
    id: 'bif',
    values: {
      code: 'BIF',
      name: 'franc burundais',
      numericCode: '108',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'bmd',
    values: {
      code: 'BMD',
      name: 'dollar bermudien',
      numericCode: '060',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bnd',
    values: {
      code: 'BND',
      name: 'dollar brunéien',
      numericCode: '096',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bob',
    values: {
      code: 'BOB',
      name: 'boliviano bolivien',
      numericCode: '068',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bov',
    values: { code: 'BOV', name: 'mvdol bolivien', numericCode: '984', decimals: 2, active: false },
  },
  {
    id: 'brl',
    values: { code: 'BRL', name: 'réal brésilien', numericCode: '986', decimals: 2, active: false },
  },
  {
    id: 'bsd',
    values: {
      code: 'BSD',
      name: 'dollar bahaméen',
      numericCode: '044',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'btn',
    values: {
      code: 'BTN',
      name: 'ngultrum bouthanais',
      numericCode: '064',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bwp',
    values: {
      code: 'BWP',
      name: 'pula botswanais',
      numericCode: '072',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'byn',
    values: {
      code: 'BYN',
      name: 'rouble biélorusse',
      numericCode: '933',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'bzd',
    values: {
      code: 'BZD',
      name: 'dollar bélizéen',
      numericCode: '084',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'cad',
    values: {
      code: 'CAD',
      name: 'dollar canadien',
      numericCode: '124',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'cdf',
    values: {
      code: 'CDF',
      name: 'franc congolais',
      numericCode: '976',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'che',
    values: { code: 'CHE', name: 'euro WIR', numericCode: '947', decimals: 2, active: false },
  },
  {
    id: 'chf',
    values: { code: 'CHF', name: 'franc suisse', numericCode: '756', decimals: 2, active: false },
  },
  {
    id: 'chw',
    values: { code: 'CHW', name: 'franc WIR', numericCode: '948', decimals: 2, active: false },
  },
  {
    id: 'clf',
    values: {
      code: 'CLF',
      name: 'unité d’investissement chilienne',
      numericCode: '990',
      decimals: 4,
      active: false,
    },
  },
  {
    id: 'clp',
    values: { code: 'CLP', name: 'peso chilien', numericCode: '152', decimals: 0, active: false },
  },
  {
    id: 'cny',
    values: {
      code: 'CNY',
      name: 'yuan renminbi chinois',
      numericCode: '156',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'cop',
    values: { code: 'COP', name: 'peso colombien', numericCode: '170', decimals: 2, active: false },
  },
  {
    id: 'cou',
    values: {
      code: 'COU',
      name: 'unité de valeur réelle colombienne',
      numericCode: '970',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'crc',
    values: {
      code: 'CRC',
      name: 'colón costaricain',
      numericCode: '188',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'cup',
    values: { code: 'CUP', name: 'peso cubain', numericCode: '192', decimals: 2, active: false },
  },
  {
    id: 'cve',
    values: {
      code: 'CVE',
      name: 'escudo capverdien',
      numericCode: '132',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'czk',
    values: {
      code: 'CZK',
      name: 'couronne tchèque',
      numericCode: '203',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'djf',
    values: {
      code: 'DJF',
      name: 'franc djiboutien',
      numericCode: '262',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'dkk',
    values: {
      code: 'DKK',
      name: 'couronne danoise',
      numericCode: '208',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'dop',
    values: {
      code: 'DOP',
      name: 'peso dominicain',
      numericCode: '214',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'dzd',
    values: { code: 'DZD', name: 'dinar algérien', numericCode: '012', decimals: 2, active: true },
  },
  {
    id: 'egp',
    values: {
      code: 'EGP',
      name: 'livre égyptienne',
      numericCode: '818',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ern',
    values: {
      code: 'ERN',
      name: 'nafka érythréen',
      numericCode: '232',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'etb',
    values: { code: 'ETB', name: 'birr éthiopien', numericCode: '230', decimals: 2, active: false },
  },
  {
    id: 'eur',
    values: { code: 'EUR', name: 'euro', numericCode: '978', decimals: 2, active: true },
  },
  {
    id: 'fjd',
    values: { code: 'FJD', name: 'dollar fidjien', numericCode: '242', decimals: 2, active: false },
  },
  {
    id: 'fkp',
    values: {
      code: 'FKP',
      name: 'livre des îles Malouines',
      numericCode: '238',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'gbp',
    values: { code: 'GBP', name: 'livre sterling', numericCode: '826', decimals: 2, active: false },
  },
  {
    id: 'gel',
    values: { code: 'GEL', name: 'lari géorgien', numericCode: '981', decimals: 2, active: false },
  },
  {
    id: 'ghs',
    values: { code: 'GHS', name: 'cédi ghanéen', numericCode: '936', decimals: 2, active: false },
  },
  {
    id: 'gip',
    values: {
      code: 'GIP',
      name: 'livre de Gibraltar',
      numericCode: '292',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'gmd',
    values: { code: 'GMD', name: 'dalasi gambien', numericCode: '270', decimals: 2, active: false },
  },
  {
    id: 'gnf',
    values: { code: 'GNF', name: 'franc guinéen', numericCode: '324', decimals: 0, active: false },
  },
  {
    id: 'gtq',
    values: {
      code: 'GTQ',
      name: 'quetzal guatémaltèque',
      numericCode: '320',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'gyd',
    values: {
      code: 'GYD',
      name: 'dollar du Guyana',
      numericCode: '328',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'hkd',
    values: {
      code: 'HKD',
      name: 'dollar de Hong Kong',
      numericCode: '344',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'hnl',
    values: {
      code: 'HNL',
      name: 'lempira hondurien',
      numericCode: '340',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'htg',
    values: {
      code: 'HTG',
      name: 'gourde haïtienne',
      numericCode: '332',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'huf',
    values: {
      code: 'HUF',
      name: 'forint hongrois',
      numericCode: '348',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'idr',
    values: {
      code: 'IDR',
      name: 'roupie indonésienne',
      numericCode: '360',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ils',
    values: {
      code: 'ILS',
      name: 'nouveau shekel israélien',
      numericCode: '376',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'inr',
    values: {
      code: 'INR',
      name: 'roupie indienne',
      numericCode: '356',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'iqd',
    values: { code: 'IQD', name: 'dinar irakien', numericCode: '368', decimals: 3, active: false },
  },
  {
    id: 'irr',
    values: { code: 'IRR', name: 'riyal iranien', numericCode: '364', decimals: 2, active: false },
  },
  {
    id: 'isk',
    values: {
      code: 'ISK',
      name: 'couronne islandaise',
      numericCode: '352',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'jmd',
    values: {
      code: 'JMD',
      name: 'dollar jamaïcain',
      numericCode: '388',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'jod',
    values: {
      code: 'JOD',
      name: 'dinar jordanien',
      numericCode: '400',
      decimals: 3,
      active: false,
    },
  },
  {
    id: 'jpy',
    values: { code: 'JPY', name: 'yen japonais', numericCode: '392', decimals: 0, active: false },
  },
  {
    id: 'kes',
    values: {
      code: 'KES',
      name: 'shilling kényan',
      numericCode: '404',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'kgs',
    values: { code: 'KGS', name: 'som kirghize', numericCode: '417', decimals: 2, active: false },
  },
  {
    id: 'khr',
    values: {
      code: 'KHR',
      name: 'riel cambodgien',
      numericCode: '116',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'kmf',
    values: { code: 'KMF', name: 'franc comorien', numericCode: '174', decimals: 0, active: false },
  },
  {
    id: 'kpw',
    values: {
      code: 'KPW',
      name: 'won nord-coréen',
      numericCode: '408',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'krw',
    values: { code: 'KRW', name: 'won sud-coréen', numericCode: '410', decimals: 0, active: false },
  },
  {
    id: 'kwd',
    values: {
      code: 'KWD',
      name: 'dinar koweïtien',
      numericCode: '414',
      decimals: 3,
      active: false,
    },
  },
  {
    id: 'kyd',
    values: {
      code: 'KYD',
      name: 'dollar des îles Caïmans',
      numericCode: '136',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'kzt',
    values: { code: 'KZT', name: 'tenge kazakh', numericCode: '398', decimals: 2, active: false },
  },
  {
    id: 'lak',
    values: { code: 'LAK', name: 'kip laotien', numericCode: '418', decimals: 2, active: false },
  },
  {
    id: 'lbp',
    values: {
      code: 'LBP',
      name: 'livre libanaise',
      numericCode: '422',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'lkr',
    values: {
      code: 'LKR',
      name: 'roupie srilankaise',
      numericCode: '144',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'lrd',
    values: {
      code: 'LRD',
      name: 'dollar libérien',
      numericCode: '430',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'lsl',
    values: { code: 'LSL', name: 'loti lesothan', numericCode: '426', decimals: 2, active: false },
  },
  {
    id: 'lyd',
    values: { code: 'LYD', name: 'dinar libyen', numericCode: '434', decimals: 3, active: false },
  },
  {
    id: 'mad',
    values: {
      code: 'MAD',
      name: 'dirham marocain',
      numericCode: '504',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mdl',
    values: { code: 'MDL', name: 'leu moldave', numericCode: '498', decimals: 2, active: false },
  },
  {
    id: 'mga',
    values: {
      code: 'MGA',
      name: 'ariary malgache',
      numericCode: '969',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mkd',
    values: {
      code: 'MKD',
      name: 'denar macédonien',
      numericCode: '807',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mmk',
    values: {
      code: 'MMK',
      name: 'kyat myanmarais',
      numericCode: '104',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mnt',
    values: { code: 'MNT', name: 'tugrik mongol', numericCode: '496', decimals: 2, active: false },
  },
  {
    id: 'mop',
    values: {
      code: 'MOP',
      name: 'pataca macanaise',
      numericCode: '446',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mru',
    values: {
      code: 'MRU',
      name: 'ouguiya mauritanien',
      numericCode: '929',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mur',
    values: {
      code: 'MUR',
      name: 'roupie mauricienne',
      numericCode: '480',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mvr',
    values: {
      code: 'MVR',
      name: 'rufiyaa maldivienne',
      numericCode: '462',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mwk',
    values: {
      code: 'MWK',
      name: 'kwacha malawite',
      numericCode: '454',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'mxn',
    values: { code: 'MXN', name: 'peso mexicain', numericCode: '484', decimals: 2, active: false },
  },
  {
    id: 'mxv',
    values: {
      code: 'MXV',
      name: 'unité de conversion mexicaine (UDI)',
      numericCode: '979',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'myr',
    values: { code: 'MYR', name: 'ringgit malais', numericCode: '458', decimals: 2, active: false },
  },
  {
    id: 'mzn',
    values: {
      code: 'MZN',
      name: 'metical mozambicain',
      numericCode: '943',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'nad',
    values: {
      code: 'NAD',
      name: 'dollar namibien',
      numericCode: '516',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ngn',
    values: { code: 'NGN', name: 'naira nigérian', numericCode: '566', decimals: 2, active: false },
  },
  {
    id: 'nio',
    values: {
      code: 'NIO',
      name: 'córdoba oro nicaraguayen',
      numericCode: '558',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'nok',
    values: {
      code: 'NOK',
      name: 'couronne norvégienne',
      numericCode: '578',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'npr',
    values: {
      code: 'NPR',
      name: 'roupie népalaise',
      numericCode: '524',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'nzd',
    values: {
      code: 'NZD',
      name: 'dollar néo-zélandais',
      numericCode: '554',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'omr',
    values: { code: 'OMR', name: 'riyal omanais', numericCode: '512', decimals: 3, active: false },
  },
  {
    id: 'pab',
    values: {
      code: 'PAB',
      name: 'balboa panaméen',
      numericCode: '590',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'pen',
    values: { code: 'PEN', name: 'sol péruvien', numericCode: '604', decimals: 2, active: false },
  },
  {
    id: 'pgk',
    values: {
      code: 'PGK',
      name: 'kina papouan-néo-guinéen',
      numericCode: '598',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'php',
    values: { code: 'PHP', name: 'peso philippin', numericCode: '608', decimals: 2, active: false },
  },
  {
    id: 'pkr',
    values: {
      code: 'PKR',
      name: 'roupie pakistanaise',
      numericCode: '586',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'pln',
    values: { code: 'PLN', name: 'zloty polonais', numericCode: '985', decimals: 2, active: false },
  },
  {
    id: 'pyg',
    values: {
      code: 'PYG',
      name: 'guaraní paraguayen',
      numericCode: '600',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'qar',
    values: { code: 'QAR', name: 'riyal qatari', numericCode: '634', decimals: 2, active: false },
  },
  {
    id: 'ron',
    values: { code: 'RON', name: 'leu roumain', numericCode: '946', decimals: 2, active: false },
  },
  {
    id: 'rsd',
    values: { code: 'RSD', name: 'dinar serbe', numericCode: '941', decimals: 2, active: false },
  },
  {
    id: 'rub',
    values: { code: 'RUB', name: 'rouble russe', numericCode: '643', decimals: 2, active: false },
  },
  {
    id: 'rwf',
    values: { code: 'RWF', name: 'franc rwandais', numericCode: '646', decimals: 0, active: false },
  },
  {
    id: 'sar',
    values: { code: 'SAR', name: 'riyal saoudien', numericCode: '682', decimals: 2, active: false },
  },
  {
    id: 'sbd',
    values: {
      code: 'SBD',
      name: 'dollar des îles Salomon',
      numericCode: '090',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'scr',
    values: {
      code: 'SCR',
      name: 'roupie des Seychelles',
      numericCode: '690',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'sdg',
    values: {
      code: 'SDG',
      name: 'livre soudanaise',
      numericCode: '938',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'sek',
    values: {
      code: 'SEK',
      name: 'couronne suédoise',
      numericCode: '752',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'sgd',
    values: {
      code: 'SGD',
      name: 'dollar de Singapour',
      numericCode: '702',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'shp',
    values: {
      code: 'SHP',
      name: 'livre de Sainte-Hélène',
      numericCode: '654',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'sle',
    values: {
      code: 'SLE',
      name: 'leone sierra-léonais',
      numericCode: '925',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'sos',
    values: {
      code: 'SOS',
      name: 'shilling somalien',
      numericCode: '706',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'srd',
    values: {
      code: 'SRD',
      name: 'dollar surinamais',
      numericCode: '968',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ssp',
    values: {
      code: 'SSP',
      name: 'livre sud-soudanaise',
      numericCode: '728',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'stn',
    values: {
      code: 'STN',
      name: 'dobra santoméen',
      numericCode: '930',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'svc',
    values: {
      code: 'SVC',
      name: 'colón salvadorien',
      numericCode: '222',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'syp',
    values: { code: 'SYP', name: 'livre syrienne', numericCode: '760', decimals: 2, active: false },
  },
  {
    id: 'szl',
    values: {
      code: 'SZL',
      name: 'lilangeni swazi',
      numericCode: '748',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'thb',
    values: {
      code: 'THB',
      name: 'baht thaïlandais',
      numericCode: '764',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'tjs',
    values: { code: 'TJS', name: 'somoni tadjik', numericCode: '972', decimals: 2, active: false },
  },
  {
    id: 'tmt',
    values: {
      code: 'TMT',
      name: 'nouveau manat turkmène',
      numericCode: '934',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'tnd',
    values: { code: 'TND', name: 'dinar tunisien', numericCode: '788', decimals: 3, active: false },
  },
  {
    id: 'top',
    values: { code: 'TOP', name: 'pa’anga tongan', numericCode: '776', decimals: 2, active: false },
  },
  {
    id: 'try',
    values: { code: 'TRY', name: 'livre turque', numericCode: '949', decimals: 2, active: false },
  },
  {
    id: 'ttd',
    values: {
      code: 'TTD',
      name: 'dollar de Trinité-et-Tobago',
      numericCode: '780',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'twd',
    values: {
      code: 'TWD',
      name: 'nouveau dollar taïwanais',
      numericCode: '901',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'tzs',
    values: {
      code: 'TZS',
      name: 'shilling tanzanien',
      numericCode: '834',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'uah',
    values: {
      code: 'UAH',
      name: 'hryvnia ukrainienne',
      numericCode: '980',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'ugx',
    values: {
      code: 'UGX',
      name: 'shilling ougandais',
      numericCode: '800',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'usd',
    values: {
      code: 'USD',
      name: 'dollar des États-Unis',
      numericCode: '840',
      decimals: 2,
      active: true,
    },
  },
  {
    id: 'usn',
    values: {
      code: 'USN',
      name: 'dollar des Etats-Unis (jour suivant)',
      numericCode: '997',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'uyi',
    values: {
      code: 'UYI',
      name: 'peso uruguayen (unités indexées)',
      numericCode: '940',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'uyu',
    values: { code: 'UYU', name: 'peso uruguayen', numericCode: '858', decimals: 2, active: false },
  },
  {
    id: 'uyw',
    values: { code: 'UYW', name: 'UYW', numericCode: '927', decimals: 4, active: false },
  },
  {
    id: 'uzs',
    values: { code: 'UZS', name: 'sum ouzbek', numericCode: '860', decimals: 2, active: false },
  },
  {
    id: 'ved',
    values: { code: 'VED', name: 'VED', numericCode: '926', decimals: 2, active: false },
  },
  {
    id: 'ves',
    values: {
      code: 'VES',
      name: 'bolivar vénézuélien',
      numericCode: '928',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'vnd',
    values: {
      code: 'VND',
      name: 'dông vietnamien',
      numericCode: '704',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'vuv',
    values: { code: 'VUV', name: 'vatu vanuatuan', numericCode: '548', decimals: 0, active: false },
  },
  {
    id: 'wst',
    values: { code: 'WST', name: 'tala samoan', numericCode: '882', decimals: 2, active: false },
  },
  {
    id: 'xad',
    values: { code: 'XAD', name: 'XAD', numericCode: '396', decimals: 2, active: false },
  },
  {
    id: 'xaf',
    values: {
      code: 'XAF',
      name: 'franc CFA (BEAC)',
      numericCode: '950',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'xcd',
    values: {
      code: 'XCD',
      name: 'dollar des Caraïbes orientales',
      numericCode: '951',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'xcg',
    values: {
      code: 'XCG',
      name: 'florin caribéen',
      numericCode: '532',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'xof',
    values: {
      code: 'XOF',
      name: 'franc CFA (BCEAO)',
      numericCode: '952',
      decimals: 0,
      active: false,
    },
  },
  {
    id: 'xpf',
    values: { code: 'XPF', name: 'franc CFP', numericCode: '953', decimals: 0, active: false },
  },
  {
    id: 'yer',
    values: { code: 'YER', name: 'riyal yéménite', numericCode: '886', decimals: 2, active: false },
  },
  {
    id: 'zar',
    values: {
      code: 'ZAR',
      name: 'rand sud-africain',
      numericCode: '710',
      decimals: 2,
      active: false,
    },
  },
  {
    id: 'zmw',
    values: { code: 'ZMW', name: 'kwacha zambien', numericCode: '967', decimals: 2, active: false },
  },
  {
    id: 'zwg',
    values: { code: 'ZWG', name: 'or du Zimbabwe', numericCode: '924', decimals: 2, active: false },
  },
]);
