// SPDX-License-Identifier: LGPL-3.0-only
//
// CSS rules of the design system (docs/design/direction-visuelle.md §7):
// - no colour is written outside the token files: every colour is a `var(--color-…)`;
// - no physical direction: only logical properties, so that right-to-left works everywhere.
const PHYSICAL_PROPERTIES = [
  'left',
  'right',
  'margin-left',
  'margin-right',
  'padding-left',
  'padding-right',
  'border-left',
  'border-right',
  'border-left-color',
  'border-left-style',
  'border-left-width',
  'border-right-color',
  'border-right-style',
  'border-right-width',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'scroll-margin-left',
  'scroll-margin-right',
  'scroll-padding-left',
  'scroll-padding-right',
];

/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'color-no-hex': [true, { message: 'Use a design token: var(--color-…).' }],
    'color-named': ['never', { message: 'Use a design token: var(--color-…).' }],
    'function-disallowed-list': [
      ['rgb', 'rgba', 'hsl', 'hsla', 'hwb', 'lab', 'lch', 'oklab', 'oklch', 'color', 'device-cmyk'],
      { message: 'Use a design token: var(--color-…).' },
    ],
    'property-disallowed-list': [
      PHYSICAL_PROPERTIES,
      { message: 'Use the logical property (inline-start, inline-end, block-start…).' },
    ],
    'declaration-property-value-disallowed-list': [
      {
        'text-align': ['left', 'right'],
        float: ['left', 'right'],
        clear: ['left', 'right'],
      },
      { message: 'Use start / end / inline-start / inline-end.' },
    ],
  },
  overrides: [
    {
      // The tokens are where the colours are defined, in a file generated by packages/ui: its
      // layout is the generator's, only the colour and direction rules apply.
      files: ['**/tokens.css'],
      rules: {
        'color-no-hex': null,
        'color-hex-length': null,
        'comment-empty-line-before': null,
        'custom-property-empty-line-before': null,
      },
    },
  ],
};
