// SPDX-License-Identifier: LGPL-3.0-only
import { randomBytes } from './signing.js';

const HEX = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, '0'));

let lastTimestamp = -1;
let lastRandom: Uint8Array = new Uint8Array(10);

/**
 * Generates a UUIDv7 (RFC 9562): 48-bit Unix time in milliseconds followed by random bits.
 * Identifiers are generated by clients (offline) and sort by creation time. Within the same
 * millisecond, the random part is incremented so that identifiers stay strictly increasing.
 * @param now - current time in milliseconds (injectable for tests)
 * @public
 */
export function uuidv7(now: number = Date.now()): string {
  let random: Uint8Array;
  if (now <= lastTimestamp) {
    now = lastTimestamp;
    random = increment(lastRandom);
  } else {
    random = randomBytes(10);
  }
  lastTimestamp = now;
  lastRandom = random;

  const bytes = new Uint8Array(16);
  let time = now;
  for (let i = 5; i >= 0; i--) {
    bytes[i] = time % 256;
    time = Math.floor(time / 256);
  }
  bytes.set(random, 6);
  bytes[6] = 0x70 | ((bytes[6] ?? 0) & 0x0f); // version 7
  bytes[8] = 0x80 | ((bytes[8] ?? 0) & 0x3f); // variant 10
  const hex = Array.from(bytes, (b) => HEX[b] ?? '00').join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function increment(previous: Uint8Array): Uint8Array {
  const next = previous.slice();
  for (let i = next.length - 1; i >= 0; i--) {
    const value = (next[i] ?? 0) + 1;
    next[i] = value & 0xff;
    if (value <= 0xff) break;
  }
  return next;
}

/**
 * Extracts the creation time (milliseconds) of a UUIDv7.
 * @public
 */
export function uuidv7Timestamp(id: string): number {
  return Number.parseInt(id.replaceAll('-', '').slice(0, 12), 16);
}
