// SPDX-License-Identifier: LGPL-3.0-only
const fr = {
  preferences: 'Préférences',
  language: 'Langue',
  theme: 'Thème',
  density: 'Densité',
  hybrid: 'Hybride',
  dark: 'Sombre',
  light: 'Clair',
  comfortable: 'Confortable',
  compact: 'Compacte',
  title: 'Votre espace de travail',
  subtitle: 'Connectez-vous pour retrouver vos données.',
  login: 'Identifiant',
  password: 'Mot de passe',
  signIn: 'Se connecter',
  loading: 'Ouverture de votre espace…',
  retry: 'Réessayer',
  logout: 'Se déconnecter',
  home: 'Mon espace',
  data: 'Mes données',
  view: 'Vue',
  record: 'Fiche',
  back: 'Retour à la liste',
  noViews: 'Aucune vue disponible',
  noViewsHint: 'Votre compte ne dispose pas de vue accessible.',
  expired: 'Votre session a expiré ou a changé. Reconnectez-vous.',
  dirty: 'Modifications en cours',
  dirtyHint: 'Votre brouillon sera perdu si vous quittez cette fiche.',
  stay: 'Rester sur la fiche',
  discard: 'Abandonner les modifications',
  verify: 'Vérifiez votre identité',
  enroll: 'Protégez votre compte',
  verifyHint: 'Utilisez une méthode de vérification activée pour votre compte.',
  enrollHint: 'Configurez une méthode pour terminer votre connexion.',
  method: 'Méthode de vérification',
  totp: 'Application d’authentification',
  recovery: 'Code de secours',
  email: 'Code par e-mail',
  passkey: 'Passkey',
  code: 'Code de vérification',
  confirm: 'Vérifier',
  restart: 'Recommencer la connexion',
  send: 'Envoyer un code',
  sent: 'La demande d’envoi a été prise en compte. Consultez votre messagerie.',
  setup: 'Configurer l’application',
  secret: 'Clé de configuration',
  secretHint: 'Ajoutez cette clé dans votre application, puis saisissez son code à six chiffres.',
  codes: 'Vos codes de secours',
  codesHint: 'Conservez ces codes dans un endroit sûr. Chacun ne peut être utilisé qu’une fois.',
  savedCodes: 'J’ai conservé mes codes',
  oidc: 'Continuer avec',
  oidcFailed: 'La connexion externe a échoué. Recommencez la connexion.',
  failed: 'Impossible d’ouvrir cette vue',
  failedHint: 'Rechargez votre espace pour continuer.',
};
export type Copy = { readonly [K in keyof typeof fr]: string };
const en: Copy = {
  preferences: 'Preferences',
  language: 'Language',
  theme: 'Theme',
  density: 'Density',
  hybrid: 'Hybrid',
  dark: 'Dark',
  light: 'Light',
  comfortable: 'Comfortable',
  compact: 'Compact',
  title: 'Your workspace',
  subtitle: 'Sign in to access your data.',
  login: 'Username',
  password: 'Password',
  signIn: 'Sign in',
  loading: 'Opening your workspace…',
  retry: 'Try again',
  logout: 'Sign out',
  home: 'My workspace',
  data: 'My data',
  view: 'View',
  record: 'Record',
  back: 'Back to list',
  noViews: 'No views available',
  noViewsHint: 'Your account has no accessible views.',
  expired: 'Your session has expired or changed. Sign in again.',
  dirty: 'Unsaved changes',
  dirtyHint: 'Your draft will be lost if you leave this record.',
  stay: 'Stay on this record',
  discard: 'Discard changes',
  verify: 'Verify your identity',
  enroll: 'Protect your account',
  verifyHint: 'Use a verification method enabled for your account.',
  enrollHint: 'Set up a method to finish signing in.',
  method: 'Verification method',
  totp: 'Authenticator app',
  recovery: 'Recovery code',
  email: 'Email code',
  passkey: 'Passkey',
  code: 'Verification code',
  confirm: 'Verify',
  restart: 'Restart sign-in',
  send: 'Send a code',
  sent: 'Your request was accepted. Check your email.',
  setup: 'Set up the app',
  secret: 'Setup key',
  secretHint: 'Add this key to your app, then enter its six-digit code.',
  codes: 'Your recovery codes',
  codesHint: 'Keep these codes in a safe place. Each can be used only once.',
  savedCodes: 'I have saved my codes',
  oidc: 'Continue with',
  oidcFailed: 'External sign-in failed. Restart sign-in.',
  failed: 'Unable to open this view',
  failedHint: 'Reload your workspace to continue.',
};
const ar: Copy = {
  preferences: 'التفضيلات',
  language: 'اللغة',
  theme: 'المظهر',
  density: 'الكثافة',
  hybrid: 'هجين',
  dark: 'داكن',
  light: 'فاتح',
  comfortable: 'مريح',
  compact: 'مضغوط',
  title: 'مساحة عملك',
  subtitle: 'سجّل الدخول للوصول إلى بياناتك.',
  login: 'اسم المستخدم',
  password: 'كلمة المرور',
  signIn: 'تسجيل الدخول',
  loading: 'جارٍ فتح مساحة عملك…',
  retry: 'إعادة المحاولة',
  logout: 'تسجيل الخروج',
  home: 'مساحتي',
  data: 'بياناتي',
  view: 'العرض',
  record: 'السجل',
  back: 'العودة إلى القائمة',
  noViews: 'لا توجد عروض متاحة',
  noViewsHint: 'لا توجد عروض متاحة لحسابك.',
  expired: 'انتهت جلستك أو تغيّرت. سجّل الدخول مجددًا.',
  dirty: 'تغييرات غير محفوظة',
  dirtyHint: 'ستفقد مسودتك إذا غادرت هذا السجل.',
  stay: 'البقاء في السجل',
  discard: 'تجاهل التغييرات',
  verify: 'تحقّق من هويتك',
  enroll: 'احمِ حسابك',
  verifyHint: 'استخدم وسيلة تحقق مفعّلة لحسابك.',
  enrollHint: 'قم بإعداد وسيلة لإتمام تسجيل الدخول.',
  method: 'وسيلة التحقق',
  totp: 'تطبيق المصادقة',
  recovery: 'رمز الاسترداد',
  email: 'رمز بالبريد الإلكتروني',
  passkey: 'مفتاح المرور',
  code: 'رمز التحقق',
  confirm: 'تحقق',
  restart: 'إعادة تسجيل الدخول',
  send: 'إرسال رمز',
  sent: 'تم قبول طلب الإرسال. راجع بريدك الإلكتروني.',
  setup: 'إعداد التطبيق',
  secret: 'مفتاح الإعداد',
  secretHint: 'أضف هذا المفتاح إلى تطبيقك، ثم أدخل الرمز المكوّن من ستة أرقام.',
  codes: 'رموز الاسترداد',
  codesHint: 'احتفظ بهذه الرموز في مكان آمن. يُستخدم كل رمز مرة واحدة فقط.',
  savedCodes: 'احتفظت برموزي',
  oidc: 'المتابعة باستخدام',
  oidcFailed: 'فشل تسجيل الدخول الخارجي. أعد تسجيل الدخول.',
  failed: 'تعذّر فتح هذا العرض',
  failedHint: 'أعد تحميل مساحة عملك للمتابعة.',
};
export function copyFor(language: string): Copy {
  return language === 'ar' ? ar : language === 'en' ? en : fr;
}
