// SPDX-License-Identifier: LGPL-3.0-only
//
// The CSS variables of the design system, generated from the tokens (`tokens.css` is the committed
// result; a test checks that it is up to date). Themes are selected by `data-theme` on the root;
// the "hybrid" theme is the default. Density by `data-density`. Motion is removed when the user
// asks for reduced motion; the narrow layout gets its own radius.
import { scale, themes, type ColorToken, type ThemeName } from './tokens.js';

const kebab = (name: string): string =>
  name.replace(/[A-Z]|\d+/g, (part) => `-${part.toLowerCase()}`);

/** `--color-<token>: value;` lines of a theme. */
function colorLines(theme: ThemeName): string {
  return (Object.entries(themes[theme]) as [ColorToken, string][])
    .map(([token, value]) => `  --color-${kebab(token)}: ${value};`)
    .join('\n');
}

/** The full stylesheet of variables. */
export function tokensCss(): string {
  const spaces = scale.space
    .map((px, index) => `  --space-${String(index)}: ${String(px)}px;`)
    .join('\n');
  return `/* SPDX-License-Identifier: LGPL-3.0-only */
/* Generated by packages/ui (src/css.ts) from src/tokens.ts: do not edit by hand. */

:root,
:root[data-theme='hybrid'] {
  color-scheme: dark;
${colorLines('hybrid')}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${colorLines('dark')}
}

:root[data-theme='light'] {
  color-scheme: light;
${colorLines('light')}
}

:root {
  --font-sans: ${scale.fontSans};
  --font-arabic: ${scale.fontArabic};
  --font-title-size: ${scale.titleSize};
  --font-title-weight: ${scale.titleWeight};
  --font-heading-size: ${scale.headingSize};
  --font-heading-weight: ${scale.headingWeight};
  --font-body-size: ${scale.bodySize};
  --font-label-size: ${scale.labelSize};
  --font-small-size: ${scale.smallSize};
  --font-small-weight: ${scale.smallWeight};
  --radius-card: ${scale.radiusCard};
  --radius-field: ${scale.radiusField};
  --radius-pill: ${scale.radiusPill};
${spaces}
  --shadow-card: none;
  --duration-fast: ${scale.durationFast};
  --duration-base: ${scale.durationBase};
  --density-row: ${scale.rowComfortable};
  --card-padding: ${scale.cardPadding};
}

:root[data-theme='light'] {
  --shadow-card: 0 1px 2px rgb(27 27 29 / 6%), 0 8px 24px rgb(27 27 29 / 6%);
}

:root[data-density='compact'] {
  --density-row: ${scale.rowCompact};
  --card-padding: ${scale.cardPaddingCompact};
}

@media (max-width: 819px) {
  :root {
    --radius-card: ${scale.radiusCardNarrow};
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
  }
}

/* Arabic: a little more line height for the diacritics. */
:lang(ar) {
  font-family: var(--font-arabic);
  line-height: 1.6;
}
`;
}
