// SPDX-License-Identifier: LGPL-3.0-only
//
// A minimal S3 client (ADR 012, maintainer's decision: in-house rather than the AWS SDK):
// put, get, delete and time-limited signed download links, with AWS Signature Version 4.
// The endpoint comes from the operator's configuration only and object keys are generated by
// the server: no URL here is ever influenced by a user (anti-SSRF).
import { createHash, createHmac } from 'node:crypto';

import { SocleError } from '@socle/framework';

export class S3Error extends SocleError {
  readonly status: number;

  constructor(message: string, status = 0) {
    super('runtime.s3', message);
    this.status = status;
  }
}

export interface S3Config {
  /** e.g. `http://seaweedfs:8333` (self-hosted) or `https://s3.gra.io.cloud.ovh.net`. */
  readonly endpoint: string;
  readonly region: string;
  readonly accessKeyId: string;
  readonly secretAccessKey: string;
  readonly bucket: string;
}

/** Object keys the server generates: `tenant/attachments/2026/09/<uuid>`. No `..`, no `//`. */
const SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const BUCKET = /^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/;
const MAX_KEY_LENGTH = 1024;

function checkKey(key: string): void {
  // Checked segment by segment (no nested quantifier, hence no catastrophic backtracking).
  if (key.length > MAX_KEY_LENGTH || !key.split('/').every((segment) => SEGMENT.test(segment))) {
    throw new S3Error(`Invalid object key "${key}".`);
  }
}

const sha256Hex = (data: string | Uint8Array): string =>
  createHash('sha256').update(data).digest('hex');
const hmac = (key: string | Buffer, data: string): Buffer =>
  createHmac('sha256', key).update(data).digest();

/** RFC 3986 encoding as S3 expects it (unreserved characters only are kept). */
function uriEncode(value: string): string {
  return encodeURIComponent(value).replace(
    /[!'()*]/g,
    (char) => `%${char.charCodeAt(0).toString(16).toUpperCase()}`,
  );
}

/** `20130524T000000Z` */
export function amzDate(date: Date): string {
  return date
    .toISOString()
    .replace(/[-:]/g, '')
    .replace(/\.\d{3}/, '');
}

export interface SigningInput {
  readonly method: string;
  /** Already encoded path, e.g. `/bucket/a%20b.txt`. */
  readonly path: string;
  readonly query?: Readonly<Record<string, string>> | undefined;
  /** Headers to sign (lowercase names), `host` included. */
  readonly headers: Readonly<Record<string, string>>;
  readonly payloadHash: string;
  readonly amzDate: string;
  readonly region: string;
  readonly accessKeyId: string;
  readonly secretAccessKey: string;
}

/**
 * AWS Signature Version 4 of a request (pure, tested against the examples of the AWS
 * documentation): the signature and the pieces of the `Authorization` header.
 */
export function signV4(input: SigningInput): {
  readonly signature: string;
  readonly credentialScope: string;
  readonly signedHeaders: string;
} {
  const date = input.amzDate.slice(0, 8);
  const credentialScope = `${date}/${input.region}/s3/aws4_request`;
  const names = Object.keys(input.headers)
    .map((name) => name.toLowerCase())
    .sort();
  const lower = new Map(
    Object.entries(input.headers).map(([name, value]) => [name.toLowerCase(), value]),
  );
  const canonicalHeaders = names
    .map((name) => `${name}:${(lower.get(name) ?? '').trim().replace(/\s+/g, ' ')}\n`)
    .join('');
  const signedHeaders = names.join(';');
  const canonicalQuery = Object.entries(input.query ?? {})
    .map(([name, value]) => [uriEncode(name), uriEncode(value)] as const)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, value]) => `${name}=${value}`)
    .join('&');
  const canonicalRequest = [
    input.method,
    input.path,
    canonicalQuery,
    canonicalHeaders,
    signedHeaders,
    input.payloadHash,
  ].join('\n');
  const stringToSign = [
    'AWS4-HMAC-SHA256',
    input.amzDate,
    credentialScope,
    sha256Hex(canonicalRequest),
  ].join('\n');
  const signingKey = hmac(
    hmac(hmac(hmac(`AWS4${input.secretAccessKey}`, date), input.region), 's3'),
    'aws4_request',
  );
  return {
    signature: createHmac('sha256', signingKey).update(stringToSign).digest('hex'),
    credentialScope,
    signedHeaders,
  };
}

export interface S3Client {
  put(key: string, body: Uint8Array, contentType: string): Promise<void>;
  /** @throws {@link S3Error} with status 404 for a missing object */
  get(key: string): Promise<Uint8Array>;
  delete(key: string): Promise<void>;
  /** A link valid `seconds` seconds (1 to 3600) to download the object without credentials. */
  presignGet(key: string, seconds: number, now?: Date): string;
  /** Creates the bucket when it does not exist yet (installation, tests). */
  ensureBucket(): Promise<void>;
}

export function createS3Client(config: S3Config): S3Client {
  if (!BUCKET.test(config.bucket)) throw new S3Error(`Invalid bucket "${config.bucket}".`);
  const endpoint = new URL(config.endpoint);
  if (endpoint.protocol !== 'https:' && endpoint.protocol !== 'http:')
    throw new S3Error('The S3 endpoint must be an http(s) URL.');
  if (endpoint.username !== '' || endpoint.password !== '')
    throw new S3Error('No credentials in the S3 endpoint URL.');
  const host = endpoint.host;
  const pathOf = (key?: string): string =>
    `/${config.bucket}${key === undefined ? '' : `/${key.split('/').map(uriEncode).join('/')}`}`;

  const request = async (
    method: 'GET' | 'PUT' | 'DELETE' | 'HEAD',
    key: string | undefined,
    body?: Uint8Array,
    contentType?: string,
  ): Promise<Response> => {
    if (key !== undefined) checkKey(key);
    const path = pathOf(key);
    const date = amzDate(new Date());
    const payloadHash = sha256Hex(body ?? '');
    const headers: Record<string, string> = {
      host,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': date,
      ...(contentType ? { 'content-type': contentType } : {}),
    };
    const { signature, credentialScope, signedHeaders } = signV4({
      method,
      path,
      headers,
      payloadHash,
      amzDate: date,
      region: config.region,
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
    });
    const sent = Object.fromEntries(Object.entries(headers).filter(([name]) => name !== 'host'));
    return fetch(`${endpoint.protocol}//${host}${path}`, {
      method,
      headers: {
        ...sent,
        authorization: `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`,
      },
      ...(body ? { body } : {}),
      redirect: 'manual',
      signal: AbortSignal.timeout(60_000),
    });
  };

  const fail = async (response: Response, what: string): Promise<never> => {
    const text = await response.text().catch(() => '');
    const code = /<Code>([^<]{1,64})<\/Code>/.exec(text)?.[1] ?? '';
    throw new S3Error(`${what}: HTTP ${String(response.status)} ${code}`.trim(), response.status);
  };

  return {
    async put(key, body, contentType) {
      const response = await request('PUT', key, body, contentType);
      if (!response.ok) await fail(response, `Cannot store ${key}`);
      await response.arrayBuffer();
    },
    async get(key) {
      const response = await request('GET', key);
      if (!response.ok) await fail(response, `Cannot read ${key}`);
      return new Uint8Array(await response.arrayBuffer());
    },
    async delete(key) {
      const response = await request('DELETE', key);
      if (!response.ok && response.status !== 404) await fail(response, `Cannot delete ${key}`);
      await response.arrayBuffer();
    },
    presignGet(key, seconds, now = new Date()) {
      checkKey(key);
      if (!Number.isInteger(seconds) || seconds < 1 || seconds > 3600)
        throw new S3Error('A download link lasts 1 to 3600 seconds.');
      const path = pathOf(key);
      const date = amzDate(now);
      const query = {
        'X-Amz-Algorithm': 'AWS4-HMAC-SHA256',
        'X-Amz-Credential': `${config.accessKeyId}/${date.slice(0, 8)}/${config.region}/s3/aws4_request`,
        'X-Amz-Date': date,
        'X-Amz-Expires': String(seconds),
        'X-Amz-SignedHeaders': 'host',
      };
      const { signature } = signV4({
        method: 'GET',
        path,
        query,
        headers: { host },
        payloadHash: 'UNSIGNED-PAYLOAD',
        amzDate: date,
        region: config.region,
        accessKeyId: config.accessKeyId,
        secretAccessKey: config.secretAccessKey,
      });
      const search = new URLSearchParams({ ...query, 'X-Amz-Signature': signature });
      return `${endpoint.protocol}//${host}${path}?${search.toString()}`;
    },
    async ensureBucket() {
      const head = await request('HEAD', undefined);
      await head.arrayBuffer();
      if (head.ok) return;
      const created = await request('PUT', undefined);
      if (!created.ok && created.status !== 409) await fail(created, 'Cannot create the bucket');
      await created.arrayBuffer();
    },
  };
}
