// SPDX-License-Identifier: LGPL-3.0-only
const words = {
  fr: {
    title: 'Échanges',
    activities: 'Mes activités',
    message: 'Message',
    note: 'Note interne',
    kind: 'Type de message',
    send: 'Publier',
    empty: 'Aucun échange pour cette fiche.',
    older: 'Messages précédents',
    follow: 'Suivre la fiche',
    unfollow: 'Ne plus suivre',
    following: 'Vous suivez cette fiche.',
    activity: 'Planifier une activité',
    summary: 'Objet',
    type: 'Type d’activité',
    due: 'Échéance',
    schedule: 'Planifier pour moi',
    done: 'Terminer',
    cancel: 'Annuler l’activité',
    feedback: 'Compte rendu',
    overdue: 'En retard',
    today: 'Aujourd’hui',
    planned: 'À venir',
    saved: 'Enregistré.',
    refreshFailed: 'Enregistré. Actualisez pour afficher les derniers échanges.',
    changed: 'Champs modifiés',
    member: 'Membre de l’équipe',
    noActivities: 'Aucune activité à faire.',
    unavailable: 'Les échanges ne sont pas disponibles.',
  },
  en: {
    title: 'Conversation',
    activities: 'My activities',
    message: 'Message',
    note: 'Internal note',
    kind: 'Message type',
    send: 'Post',
    empty: 'No conversation on this record.',
    older: 'Earlier messages',
    follow: 'Follow record',
    unfollow: 'Unfollow',
    following: 'You follow this record.',
    activity: 'Schedule an activity',
    summary: 'Summary',
    type: 'Activity type',
    due: 'Due date',
    schedule: 'Schedule for me',
    done: 'Complete',
    cancel: 'Cancel activity',
    feedback: 'Feedback',
    overdue: 'Overdue',
    today: 'Today',
    planned: 'Upcoming',
    saved: 'Saved.',
    refreshFailed: 'Saved. Refresh to see the latest conversation.',
    changed: 'Fields changed',
    member: 'Team member',
    noActivities: 'No activities to complete.',
    unavailable: 'Conversations are unavailable.',
  },
  ar: {
    title: 'المحادثة',
    activities: 'أنشطتي',
    message: 'رسالة',
    note: 'ملاحظة داخلية',
    kind: 'نوع الرسالة',
    send: 'نشر',
    empty: 'لا توجد محادثة لهذا السجل.',
    older: 'الرسائل السابقة',
    follow: 'متابعة السجل',
    unfollow: 'إلغاء المتابعة',
    following: 'أنت تتابع هذا السجل.',
    activity: 'جدولة نشاط',
    summary: 'الموضوع',
    type: 'نوع النشاط',
    due: 'تاريخ الاستحقاق',
    schedule: 'جدولة لي',
    done: 'إكمال',
    cancel: 'إلغاء النشاط',
    feedback: 'التقرير',
    overdue: 'متأخر',
    today: 'اليوم',
    planned: 'قادم',
    saved: 'تم الحفظ.',
    refreshFailed: 'تم الحفظ. حدّث لعرض أحدث المحادثات.',
    changed: 'الحقول المعدلة',
    member: 'عضو الفريق',
    noActivities: 'لا توجد أنشطة لإكمالها.',
    unavailable: 'المحادثات غير متاحة.',
  },
} as const;

export const threadCopy = (language: string) =>
  language.startsWith('ar') ? words.ar : language.startsWith('fr') ? words.fr : words.en;
export function activityTypeName(code: string, fallback: string, language: string): string {
  const labels: Readonly<Record<string, readonly [string, string, string]>> = {
    call: ['Appel', 'Call', 'مكالمة'],
    email: ['E-mail', 'Email', 'بريد إلكتروني'],
    meeting: ['Réunion', 'Meeting', 'اجتماع'],
    todo: ['À faire', 'To do', 'مهمة'],
  };
  return (
    labels[code]?.[language.startsWith('ar') ? 2 : language.startsWith('fr') ? 0 : 1] ?? fallback
  );
}
